services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      ROCKET_ADDRESS: "0.0.0.0"

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
